---
version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "REPLACE_TASK_DEFINITION"
        LoadBalancerInfo:
          ContainerName: "web"
          ContainerPort: 80
