version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: karrio_app
    ports:
      - "5002:5002"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: karrio
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: