name: Deploy via CodeDeploy

on:
  workflow_dispatch:

jobs:
  codedeploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Upload and Deploy via CodeDeploy
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          ARCHIVE_NAME=deployment-$TIMESTAMP.zip
          BUCKET=${{ secrets.S3_BUCKET_NAME }}

          zip -r $ARCHIVE_NAME appspec.yaml scripts/
          aws s3 cp $ARCHIVE_NAME s3://$BUCKET/$ARCHIVE_NAME

          DEPLOYMENT_JSON=$(jq -n             --arg bucket "$BUCKET"             --arg key "$ARCHIVE_NAME"             '{revisionType: "S3", s3Location: {bucket: $bucket, key: $key, bundleType: "zip"}}')

          DEPLOYMENT_ID=$(aws deploy create-deployment             --application-name frontend-deploy             --deployment-group-name frontend-deploy-group             --deployment-config-name CodeDeployDefault.ECSAllAtOnce             --revision "$DEPLOYMENT_JSON"             --description "Deploy from GitHub Actions with AppSpec"             | jq -r '.deploymentId')

          if [ -z "$DEPLOYMENT_ID" ]; then
            echo "Failed to get a deployment ID"
            exit 1
          fi

          echo "Deployment ID: $DEPLOYMENT_ID"

          echo "Waiting for deployment to complete..."
          aws deploy wait deployment-successful --deployment-id "$DEPLOYMENT_ID"

          echo "Deployment completed!"
          aws deploy get-deployment --deployment-id "$DEPLOYMENT_ID"

