name: Deploy to ECS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Register New Task Definition and Update ECS Service
        env:
          CLUSTER: application_cluster
          SERVICE: frontend
          IMAGE_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest
        run: |
          TASK_DEF_ARN=$(aws ecs describe-services --cluster $CLUSTER --services $SERVICE             | jq -r '.services[0].taskDefinition')

          aws ecs describe-task-definition --task-definition $TASK_DEF_ARN             | jq 'del(
                .taskDefinition.taskDefinitionArn,
                .taskDefinition.revision,
                .taskDefinition.status,
                .taskDefinition.requiresAttributes,
                .taskDefinition.compatibilities,
                .taskDefinition.registeredAt,
                .taskDefinition.registeredBy,
                .taskDefinition.deregisteredAt
              )
              | .taskDefinition
              | with_entries(select(.value != null))' > new-task-def.json

          jq --arg IMAGE "$IMAGE_URI"             '.containerDefinitions[0].image = $IMAGE' new-task-def.json > tmp.json && mv tmp.json new-task-def.json

          NEW_TASK_DEF_ARN=$(aws ecs register-task-definition             --cli-input-json file://new-task-def.json             | jq -r '.taskDefinition.taskDefinitionArn')

          aws ecs update-service --cluster $CLUSTER             --service $SERVICE             --task-definition $NEW_TASK_DEF_ARN