name: ECS Blue/Green Deploy via CodeDeploy (S3 ZIP)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Package AppSpec and scripts into ZIP
        run: |
          mkdir -p bundle/scripts
          cp appspec.yaml bundle/
          cp scripts/*.sh bundle/scripts/
          cd bundle
          zip -r ../code.zip .
          cd ..

      - name: Upload ZIP to S3
        run: |
          aws s3 cp code.zip s3://${{ secrets.S3_BUCKET_NAME }}/code.zip

      - name: Trigger CodeDeploy Deployment
        run: |
          aws deploy create-deployment \
            --application-name frontend-deploy \
            --deployment-group-name frontend-deploy-group \
            --deployment-config-name CodeDeployDefault.ECSAllAtOnce \
            --revision '{
              "revisionType": "S3",
              "s3Location": {
                "bucket": "${{ secrets.S3_BUCKET_NAME }}",
                "key": "code.zip",
                "bundleType": "zip"
              }
            }'