name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform  # adjust this if your `.tf` files are elsewhere

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="ami_id=ami-0c12f1613ee864d3f" \
            -var="aws_account_id=${{ secrets.AWS_ACCOUNT_ID }}" \
            -var="aws_account_region=${{ secrets.AWS_REGION }}" \
            -var="certificate_arn=${{ secrets.CERTIFICATE_ARN }}" \
            -var="key_name=${{ secrets.KEY_NAME }}"  \
            -var="lb_target_group_443_name=${{ secrets.LB_TG_443_NAME }}"


      - name: Terraform Apply
        run: terraform apply -auto-approve -var="ami_id=ami-0c12f1613ee864d3f"
